### ISSUE TITLE
The line with the check!

### ISSUE THREAD

**Issue by skozlovskiy** [CheckiO-Missions/checkio-mission-sort-by-extension#6]
The line with the check

`assert sort_by_ext(['1.cad', '1.bat', '1.aa', '.bat']) == ['.bat', '1.aa', '1.bat', '1.cad']`
In the requirements first, you ask to sort by extension and only then by the name of the file.

So I'm sure that this check should look like this:
`assert sort_by_ext(['1.cad', '1.bat', '1.aa', '.bat']) == ['1.aa', '.bat', '1.bat', '1.cad']`

Am I right?

Here is the code you can try:
```python

def sort_by_ext(files: List[str]) -> List[str]:
    _files = [x.split('.') for x in files]
    return ['.'.join(i) for i in sorted(_files, key=itemgetter(-1, 0))]
```

**Comment by oduvan** [comment]
"Filename ".config" has an empty extension and a name ".config";"
